name: cosmic
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/planets/
    - assets/svg/


  fonts:
    - family: GothamPro
      fonts:
        - asset: assets/fonts/GothamPro-Bold.ttf
        - asset: assets/fonts/GothamPro-Medium.ttf
        - asset: assets/fonts/GothamPro-Regular.ttf
        - asset: assets/fonts/GothamPro.ttf
